### ISSUE TITLE
Vue: implement 'Detect and Select' component(s)

### ISSUE THREAD

**Issue by isms** [concept-to-clinic/concept-to-clinic#148] opened 2017-10-05 21:19 UTC
### This issue will remain open until all the checkboxes are checked! PRs can reference this issue and will get credit even if the whole issue is not yet closed :+1:

Note: split off from #110, interaction with imagery tracked in #179 

---

Design doc reference here: http://concept-to-clinic.readthedocs.io/en/latest/design-doc.html#detect-and-select

Mock-up:
![](http://concept-to-clinic.readthedocs.io/en/latest/_images/wireframe-1-detect-and-select.svg)

## Expected Behavior
Users should be able to view predictions of nodule centroids and mark whether they are concerning or not:

- [ ] List all available predicted candidate sites. Allow each to be selected to view details.
- [ ] When a candidate is selected, show a detail view in an image viewer control. By default, show the slice containing the predicted centroid and a marker clearly indicating where the predicted centroid occurs.
- [ ] Allow the user to zoom, pan, and navigate through slices in the image viewer.
- [ ] Allow the user to window grayscale levels.
- [ ] Allow the user to toggle the candidate centroid marker’s visibility.
- [ ] Allow the user to mark any predicted candidate for further analysis.
- [ ] Allow the user to navigate through the imagery freestyle and mark other locations which the models missed.
- [ ] When the user has finished marking candidates, send all of this labeled data to the backend in the format specified above.

## Possible Implementation
Basic Django templates were created for this in #88 - that is probably a good place to start.

## Mocking data

Feel free to mock data for `state` if it is not yet implemented in the backend API, and feel free to `POST` to API endpoints that don't exist yet :sparkles:

**Comment by lmiller1990** [comment] 2017-10-06 14:13
Hi. I love what the project is looking to achieve and am a great supporter of the cause. I've done a lot of Vue.js, so I'm going to try and start building some of the UI related issues.

**Comment by isms** [comment] 2017-10-06 14:40
@lmiller Glad to have you on board! :boat:

**Comment by lmiller1990** [comment] 2017-10-09 14:55
Thanks. I'll see if I can get something done in the next few days, got everything up and running plus created some fake data.

Project is still early days - there aren't any models or much else in terms of data set up yet, should I just fake/make it up for now?

**Comment by stranger26** [comment] 2017-10-09 15:09
@lmiller1990 I think you should just fake it, at least that is from what I understand from the 'Mocking data' section.

**Comment by isms** [comment] 2017-10-11 01:45
@lmiller1990 @stranger26 New info on getting test data [here] - I also opened #153 to publicize this more.

**Comment by swederik** [comment] 2017-10-18 17:32
Cool project! Looks like you guys could build this piece with Cornerstone pretty easily. Here are some links that might help:

Image tools: https://rawgit.com/chafey/cornerstoneTools/master/examples/allImageTools/index.html
Stack Scroll tool: https://rawgit.com/chafey/cornerstoneTools/master/examples/stackScroll/index.html
Crosshairs: https://rawgit.com/chafey/cornerstoneTools/master/examples/crosshairs/index.html
DICOM Web access: https://rawgit.com/chafey/cornerstoneWADOImageLoader/master/examples/wadouri/index.html

**Comment by louisgv** [comment] 2017-10-20 13:58
Is this issue being worked on? If not I will be looking at implementing it next week.

**Comment by antonow** [comment] 2017-10-21 18:59
Where can we find some sample DICOM image data? I didn't see anything in the developer documentation. Should we just pull from the internet for now?

**Comment by louisgv** [comment] 2017-10-22 03:35
@antonow are you working on this component?

**Comment by isms** [comment] 2017-10-22 15:26
@antonow Check out the `/tests/assets` directory for example imagery.

**Comment by antonow** [comment] 2017-10-23 23:09
@louisgv I was thinking about it, but no I am not currently working on this.

**Comment by louisgv** [comment] 2017-10-24 09:22
@antonow I will be tackling #182 then, since you probably got a plan to get this done. (I've not give it any thought yet :p )

**Comment by Serhiy-Shekhovtsov** [comment] 2017-11-07 19:22
I'm taking this issue, if nobody minds.

**Comment by lamby** [comment] 2017-11-23 01:12
Fixed in https://github.com/concept-to-clinic/concept-to-clinic/commit/093b06ffddf7a38b73a703ac2ecd28c33db386a3

**Comment by lamby** [comment] 2017-12-01 09:07
Merged in https://github.com/concept-to-clinic/concept-to-clinic/commit/c4db12ee26b004f1c7466fb879bfe36ea6135048: )

**Comment by Serhiy-Shekhovtsov** [comment] 2017-12-17 10:22
@lamby this can be closed, right?

**Closed** 2017-12-18 14:32 UTC
Labels: feature, interface-frontend, medium, official, POINT-BOUNTY
