### ISSUE TITLE
Travis: "Could not find repository"

### ISSUE THREAD

**Issue by WGierke** [concept-to-clinic/concept-to-clinic#63] opened 2017-08-22 15:18 UTC
When trying to see the Travis logs of a build, you end up on a Travis page stating "We couldn't find the repository concept-to-clinic/concept-to-clinic".

## Expected Behavior
When trying to access the Travis logs of a build, you should be able to see the logs of the respective build.

## Current Behavior
You see the described error page.

## Possible Solution
Are the builds only visible to admins? If so, it might be helpful to change some access rights.

## Steps to Reproduce
Check a build like [this one](https://travis-ci.com/concept-to-clinic/concept-to-clinic/builds/52855581?utm_source=github_status&utm_medium=notification)

## Context (Environment)
I want to see any problems that occurred when running a Travis build.

## Detailed Description
Contributors should be able to access the Travis logs so they know what went wrong.

## Checklist before submitting
- [X] I have confirmed this using the officially supported Docker Compose setup using the `local.py` configuration and ensured that I built the containers again and they reflect the most recent version of the project at the `HEAD` commit on the `master` branch 
- [X] I have searched through the other currently open issues and am confident this is not a duplicate of an existing bug
- [X] I provided a **minimal code snippet** or list of steps that reproduces the bug.
- [X] I provided **screenshots** where appropriate
- [X] I filled out all the relevant sections of this template

**Comment by isms** [comment] 2017-08-22 15:28
@WGierke Thanks for reporting. I can reproduce this in an incognito window, but can you confirm you authed with Github?
![image](https://user-images.githubusercontent.com/1284973/29573462-05a06f84-872d-11e7-9241-d8275bee8d7e.png)

**Comment by WGierke** [comment] 2017-08-22 15:31
Hey @isms Thanks for your fast comment! Sorry for the missing screenshot but yes, I can confirm it even when I'm logged in 
![screenshot from 2017-08-22 17-30-44](https://user-images.githubusercontent.com/6676439/29573624-bfe82be8-875f-11e7-96f5-b7bc8e153833.png)

**Comment by isms** [comment] 2017-08-22 15:38
@WGierke Got it, this is weird and I've reported to Travis. Will update when we hear back!

**Comment by isms** [comment] 2017-08-23 17:22
It turns out we were still using travis-ci.com from before the private -> public switch was flipped on this repo. Now it's all set on travis-ci.org as a public repo. You should see the newer builds (currently failing due to LFS bandwidth issues :crying_cat_face:) on the .org side.

Thanks @WGierke for reporting and investigating. Closing.

**Closed by isms** 2017-08-23 17:22 UTC
